// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NewProject2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240414202320_connectToDatabase")]
    partial class connectToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewProject2.Models.Student", b =>
                {
                    b.Property<string>("SubjectName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("InternalMarksMaximum")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("InternalMarksSecured")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("SemesterMarksMaximum")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("SemesterMarksSecured")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("SubjectName");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
